### ISSUE TITLE
Maintainer to-do list (English Glossary)

### ISSUE THREAD

**Issue by CathPag** [cncf/glossary#1535]
- [x] [Policy as code](https://github.com/cncf/glossary/blob/main/content/en/policy-as-code.md): is merged but not completed. Determine next steps
- [x] Rework microservices definition to microservices architecture and adjust services definition accordingly 
- [ ] Finish [data center](https://github.com/cncf/glossary/pull/1541)
- [ ] GitOps term
- [ ] Revisit observability
- [ ] Review each term and determine if updates are needed
- [x] [Canary definition tweak](https://github.com/cncf/glossary/issues/736) >> no update needed

**Comment by iamNoah1** [comment]
regarding Policy as Code, what exactly is not complete about the article? When we have that, we could open an issue with the information about what has to be done.

**Comment by CathPag** [comment]
Not sure. Just ticked it off.

**Comment by jihoon-seo** [comment]
- Policy as Code: has been promoted to "Completed", is [live on website](https://glossary.cncf.io/policy-as-code/).
- Microservices Architecture: done via the PR #1549
- Data Center: updated via #1541
- GitOps: added via #302 as "Feedback Appreciated", so not displayed on website for now.
- Observability: updated via #1668
- https://github.com/cncf/glossary/issues/736 >> no update needed

It seems that all items in checklist are resolved, except whether promote "GitOps" to "Completed" or not.
We can open a new issue if another judgement regarding that is needed.
