### ISSUE TITLE
[tw] Initial merging the `dev-tw` branch into main branch

### ISSUE THREAD

**Issue by ydFu** [cncf/glossary#2355]
## Merging the localization branch into main branch

After completing the minimum required terms for a new localization, open a PR to merge commits in the localization branch into the main branch.
Ref: [Localization-step5](https://github.com/cncf/glossary/blob/main/LOCALIZATION.md#5-merging-the-localization-branch-into-main-branch)

### Task
- [x] Add acknowledgement for initial localization contributors list (add localization acknowledge after maintainers acknowledge section in the index page) 
  - [x] (english update) [content/en/_index.md](https://github.com/cncf/glossary/pull/2343/files#diff-f1f180e860deaa9c82eefe2a7a7102cc1cfeb159e7271758996b608ccf81cef9)
  - [x] https://github.com/cncf/glossary/issues/2357
  - [x] https://github.com/cncf/glossary/pull/2363
- [x] Update dev-tw based on the latest main.
  - [x] https://github.com/cncf/glossary/pull/2461 
  - [x] https://github.com/cncf/glossary/pull/2485
  - [x] https://github.com/cncf/glossary/pull/2517
  - [x] https://github.com/cncf/glossary/pull/2572
  - [x] Last confirmation date: 2023/11/01
- [x] Update outdated tw contents.
  - [x] (english update) [content/en/contribute/_index.md](https://github.com/cncf/glossary/pull/2343/files#diff-876ed670f5369381fd171c016547005170366cfd45cae03f3b95c4d4b8f0461d) 
  - [x] https://github.com/cncf/glossary/issues/2356
  - [x] https://github.com/cncf/glossary/issues/2330
  - [x] https://github.com/cncf/glossary/pull/2283
  - [x] https://github.com/cncf/glossary/issues/2413
  - [x] Last confirmation date: 2023/11/01
- [ ] Open a PR to merge dev-tw into the main branch. 
  - [ ] https://github.com/cncf/glossary/pull/2576 

### Checklist
- [x] validate all files which are not in the localization directory (content/ur/*)
  - [x]  Last confirmation date: 2023/11/01
- [x] check i18n/ur.toml exist and localized
  - [x]  Last confirmation date: 2023/11/01
- [x] check l10n configuration in config.toml
  - [x]  Last confirmation date: 2023/11/01
- [x] acknowledge to initial localization contributors list (add localization acknowledge after maintainers acknowledge section in the index page)
  - [x]  Last confirmation date: 2023/11/01
- [x] check build and Preview works

**Comment by pichuang** [comment]
Reference PR https://github.com/cncf/glossary/pull/2358

**Comment by ydFu** [comment]
> Reference PR #2358
Thanks for the reminder, I’ll update it
