### ISSUE TITLE
[tw] Remove "What it is" section

### ISSUE THREAD

**Issue by tico88612** [cncf/glossary#2662]
Follow this discussion https://github.com/cncf/glossary/issues/2575

## Update latest

- [x] agile-software-development #2846
- [x] api-gateway #2846
- [x] application-programming-interface #2846
- [x] blue-green-deployment #2846
- [x] canary-deployment #2846
- [x] chaos-engineering #2891
- [x] client-server-architecture #2891
- [x] cloud-computing #2891
- [x] cloud-native-tech #2891
- [x] cluster #2891
- [ ] container-orchestration
- [ ] container
- [x] continuous-delivery #2924
- [x] continuous-deployment #2924
- [x] continuous-integration #2924
- [x] devops #2924
- [x] devsecops #2924
- [ ] distributed-apps
- [ ] distributed-systems
- [ ] ebpf
- [ ] edge-computing
- [ ] function-as-a-service
- [ ] horizontal-scaling
- [ ] idempotence
- [ ] infrastructure-as-code
- [ ] kubernetes
- [ ] microservices-architecture
- [ ] monolithic-apps
- [ ] multitenancy
- [ ] mutual-transport-layer-security
- [ ] nodes
- [ ] observability
- [ ] pod
- [ ] reliability
- [ ] scalability
- [ ] serverless
- [ ] service-mesh
- [ ] service
- [ ] shift-left
- [ ] site-reliability-engineering
- [ ] transport-layer-security
- [ ] vertical-scaling
- [ ] virtual-machine
- [ ] virtualization
- [ ] zero-trust-architecture

**Comment by draunger** [comment]
Assign me

**Comment by draunger** [comment]
@tico88612 can i start working on this??
