### ISSUE TITLE
Tracking Hindi Localization Progress of Glossary

### ISSUE THREAD

**Issue by Garima-Negi** [cncf/glossary#270]
This issue tracks Hindi localization progress.

### Checklist to translate a term
1. Check that no one else has claimed the page in the comments below.
2. Comment below the page that you would like to localize, focus on one page per PR, at a time.
3. Maintainers will add your username and Pull Request next to your selected page in below checklist.
4. Fork this repo, make your localizations, and submit a pull request following the name convention [hi] [page name from task]. 
5. tag/ping a maintainer to make it easier to track progress

**Points to remember:**
- Please use the word localization instead of translation.
- For any queries, feel free to contact us in [Slack channel](https://cloud-native.slack.com/archives/C02PCHEQXK6)
- For more information on how to contribute, check out [guidelines](https://glossary.cncf.io/contribute/)

### For Volunteers
Volunteers can comment below on this issue with the page-name they are interested in localizing. 
Please also provide a placeholder PR in your comment.
Example: ` I would like to help with/take up/localize page xyz.md . Here's a placeholder PR for the same.`

### To create a PR:
- Fork [https://github.com/cncf/glossary/tree/dev-hi](https://github.com/cncf/glossary/tree/dev-hi) repository to your personal account
- Create a branch with name suitable for your assigned task `e.g. Localize content/hi/style-guide/_index.md`
- Once the changes are made, create a pull request (PR) against `cncf:dev-hi` from `<your-github-id>:<branch-name>`
- Mention this [issue](https://github.com/cncf/glossary/issues/270#issuecomment-998098556) in the PR description
- NOTE: Please create 1 PR for a single page from tasks below. This makes it easier to track progress.

### For Maintainers
Volunteers will comment below on this issue with the page-name. 
Maintainers will add their username and PR next to the task.
Example : `Autoscaling Hindi localization (@contributor-username) #<PR link>`
Regularly check for PRs merged and subsequently mark the task done in this issue.

### Priorities
We need at least 10 terms in Hindi before go live, below are some suggested terms to work:

Minimum 10 terms required: 
- [x] config.toml
   content/hi/_index.md
   content/hi/_TEMPLATE.md
   content/hi/cloud_native_tech.md
   content/hi/contribute/_index.md
   content/hi/style-guide/_index.md
   i18n/hi.toml
   content/hi/_TEMPLATE.md
   @anubha-v-ardhan 
   #300 
- [x] content/hi/abstraction.md 
  @Shubh28698 
  #355 
- [x] content/hi/agile_software_development.md 
  @anubha-v-ardhan 
  #377 
- [x] content/hi/auto_scaling.md 
  @ShivamTyagi12345
  #393 
- [x] content/hi/continuous_delivery.md
  @verma-kunal
  #401 
- [x] content/hi/continuous_integration.md
  @Aayush987
  #420 
- [x] content/hi/containerization.md 
   @verma-kunal
  #383 
- [x] content/hi/devops.md
  @anubha-v-ardhan 
  #381 
- [x] content/hi/container.md 
  @kranurag7
  #394 
- [x] content/hi/container-image.md
   @Garima-Negi
   #417 
- [x] content/hi/contributor-ladder/_index.md
  @Garima-Negi 
  #503 

Additional good to have terms: 
- [ ] content/hi/api_gateway.md
  @ShivamTyagi12345
- [x] content/hi/canary_deployment.md
  @Aayush987
  #421 
- [ ] content/hi/client_server_architecture.md
  @verma-kunal
  #520 
- [ ] content/hi/cloud_native_apps.md
  @anubha-v-ardhan 
- [ ] content/hi/cloud_native_security.md
  @kranurag7
- [ ] content/hi/application_programming_interface.md 
  @WebShivam 
- [ ] content/hi/cloud_computing.md 
   @Shubh28698
- [ ] content/hi/cluster.md 
  @rajatgupta24
  #378
- [ ] automation.md
  @unnati914
  #488 
- [ ] content/hi/bare_metal_machine.md
  @anubhav06
  #490 
- [ ] content/hi/blue_green_deployment.md
  @Shivansh-yadav13
- [ ] TLS(Transport Layer Security).md
  @gullapalli9482

**Comment by sayantani11** [comment]
@sayantani11 - I can review the PRs and contribute as well

**Comment by sayantani11** [comment]
I can review the PRs, but will require someone else as well

**Comment by anubha-v-ardhan** [comment]
> I can review the PRs, but will require someone else as well

I can help now that K8s hindi documentation is about to launch, I can find time to review PRs here.

**Comment by anubha-v-ardhan** [comment]
@Garima-Negi I believe, we will also need Site strings i.e. `i18n/hi.toml` as a minimum requirement. Can you add it to the checklist.

**Comment by anubha-v-ardhan** [comment]
> I can review the PRs, but will require someone else as well

I can help with review and approval work too

**Comment by jayesh-srivastava** [comment]
I would like to assist too.
> I can review the PRs, but will require someone else as well

**Comment by jayesh-srivastava** [comment]
@Garima-Negi Also I think a new language block for Hindi is to be added in `config.toml` right?

**Comment by anubha-v-ardhan** [comment]
@jayesh-srivastava yes!

**Comment by jayesh-srivastava** [comment]
@anubha-v-ardhan I guess one page per PR would be great unlike how the Korean team did because then it would be a difficult process to review such huge PRs.

**Comment by anubha-v-ardhan** [comment]
@jayesh-srivastava Not exactly like that. I was saying the initilization of new localization can be done in one PR. i.e just `configs.toml` and `CODEOWNERS`. Sorry for miscommunication

**Comment by sayantani11** [comment]
> > I can review the PRs, but will require someone else as well
> 
> I can help with review and approval work too

Yeah review and approval

**Comment by verma-kunal** [comment]
Awesome! I would love to join in as an approver from the next month as well, to help out 🙂

**Comment by anubha-v-ardhan** [comment]
@Garima-Negi I believe we'll also need site strings as minimum requirements, Can we add it to the checklist

**Comment by sayantani11** [comment]
content/hi/_TEMPLATE.md
content/hi/_index.md
content/hi/contribute/_index.md
i18n/hi.toml
Solved in #349

**Comment by ShivamTyagi12345** [comment]
I would like to take up content/hi/auto_scaling.md to get started @Garima-Negi

**Comment by Garima-Negi** [comment]
> I would like to take up content/hi/auto_scaling.md to get started @Garima-Negi

Hi Shivam, I have updated your name in the list above. Whenever you're ready with a placeholder PR, do share it here or on slack. Thank you!

**Comment by Shubh28698** [comment]
@Garima-Negi I would like to take content/hi/_TEMPLATE.md

**Comment by anubha-v-ardhan** [comment]
@Shubh28698
content/hi/_TEMPLATE.md
content/hi/_index.md
content/hi/contribute/_index.md
and i18n/hi.toml 
have been localized by @sayantani11. see https://github.com/cncf/glossary/issues/270#issuecomment-1019583345
You can take any other file than this

**Comment by Shubh28698** [comment]
> @Shubh28698 content/hi/_TEMPLATE.md content/hi/_index.md content/hi/contribute/_index.md and i18n/hi.toml have been localized by @sayantani11. see [#270 (comment)](https://github.com/cncf/glossary/issues/270#issuecomment-1019583345) You can take any other file than this. Also check recent comments along with the checklist as the checklist maybe lagging a bit as updating it is a manual work.
> 
> @Garima-Negi, can you mark all the above pages on checklist

Sry @anubha-v-ardhan , Then i will take content/hi/abstraction.md

**Comment by anubha-v-ardhan** [comment]
I'm working on `content/hi/agile_software_development.md`

**Comment by anubha-v-ardhan** [comment]
I'll take `content/hi/agile_software_development.md`

**Comment by WebShivam** [comment]
Hi @Garima-Negi, I would like to take content/hi/application_programming_interface.md to get started with the localization

**Comment by Shubh28698** [comment]
Hi @Garima-Negi , I would like to take content/hi/cloud_computing.md

**Comment by anubha-v-ardhan** [comment]
@Garima-Negi #349  is closed (ref. https://github.com/cncf/glossary/pull/300#issuecomment-1024894288)

I'll be adding the following pages via #300 
- config.toml
- content/hi/_index.md
- content/ko/cloud_native_tech.md
- content/hi/contribute/_index.md
- content/hi/style-guide/_index.md
- i18n/hi.toml

PR #300 will test our config for Hindi localization works. Please mark these pages on the checklist as assigned

**Comment by anubha-v-ardhan** [comment]
@Garima-Negi `content/hi/style-guide/_index.md` and ` content/hi/cloud_native_tech.md` are written as separate points too while they are being covered by #300. Please remove them from checklist to avoid confusion.

Also add `content/hi/_TEMPLATE.md` being covered by #300 itself

**Comment by anubha-v-ardhan** [comment]
Next working on ` content/hi/devops.md` :)

**Comment by rajatgupta24** [comment]
Hey everyone, I'll be working on `content/hi/cluster.md`.

**Comment by jayesh-srivastava** [comment]
A small reminder for everyone, please use the label 'lang/hi' with your PR. Thanks!

**Comment by anubha-v-ardhan** [comment]
> A small reminder for everyone, please use the label 'lang/hi' with your PR. Thanks!

@jayesh-srivastava Everyone can't edit labels on PRs. We maintainers have the rsponsibility to assign appropriate labels

**Comment by jayesh-srivastava** [comment]
@anubha-v-ardhan Oh okay! Got it.

**Comment by verma-kunal** [comment]
Hey all, i would be starting to work on `content/hi/containerization.md` :)

**Comment by kranurag7** [comment]
Hey Everyone, I would be love to work on `content/hi/container.md` and `content/hi/container-image.md`

**Comment by anubha-v-ardhan** [comment]
@kranurag7 Please only take one page at a time. Assigning `content/hi/container.md` to you

**Comment by kranurag7** [comment]
Sure @anubha-v-ardhan I will work on this. Thank you for assigning.

**Comment by ShivamTyagi12345** [comment]
will work next on content/hi/_index.md

**Comment by anubha-v-ardhan** [comment]
> will work next on content/hi/_index.md

content/hi/_index.md is already localized with PR #300 as shown in the cheklist above. Please choose something else.

**Comment by ShivamTyagi12345** [comment]
> * content/hi/api_gateway.md

Thats on me. Thanks. I will choose content/hi/api_gateway.md

**Comment by Aayush987** [comment]
Hi I would love to contribute to this issue.I would like to take  content/hi/client_server_architecture.md file.If anyone is not working on it please assign it to me.

**Comment by kranurag7** [comment]
@Aayush987 Thanks for coming up. The issue will be assigned to you if no one is working on it.

**Comment by Aayush987** [comment]
@kranurag7 Thanks

**Comment by Aayush987** [comment]
I wanted to ask if i have to do it via cloning on my system or i can simply do it in github on browser?

**Comment by kranurag7** [comment]
@Aayush987 You can do it in browser only. Cloning is not required but still if you want to clone then go ahead.

**Comment by anubha-v-ardhan** [comment]
Thanks @Aayush987. I've assigned the requested page to you. Please also consider joining #glossary-localization and @glossary-localization-hindi on CNCF Slack for discussions or conversations of any kind.

>I wanted to ask if i have to do it via cloning on my system or i can simply do it in github on browser?

I's not sure if we can branch from `dev-hi` on GitHub itself. If yes, I see no harm in doing so. Note that the PR will have to target `dev-hi` and not main

**Comment by Aayush987** [comment]
> Thanks @Aayush987. I've assigned the requested page to you. Please also consider joining #glossary-localization and #glossary-localization-hindi on CNCF Slack for discussions or conversations of any kind.
> 
> > I wanted to ask if i have to do it via cloning on my system or i can simply do it in github on browser?
> 
> I's not sure if we can branch from `dev-hi` on GitHub itself. If yes, I see no harm in doing so. Note that the PR will have to target `dev-hi` and not `main`

Can you please send me CNCF slack link . I cant find it?

**Comment by kranurag7** [comment]
I would be working on `content/hi/cloud_native_security.md`.

**Comment by Aayush987** [comment]
My previous Pr on ` content/hi/continuous_integration.md` just needs approval , now i would like to work on ` content/hi/canary_deployment.md`.Plz assign it to me

**Comment by Garima-Negi** [comment]
Updated [https://github.com/cncf/glossary/pull/417](https://github.com/cncf/glossary/pull/417) to tracking issue

**Comment by Garima-Negi** [comment]
Hi, @Shubh28698 and @WebShivam!
 
 Thank you for signing up for your respective pages.
 We would like to get placeholder PRs for the same if you have begun work on the localization already. 
 Please also paste the tracking issue `https://github.com/cncf/glossary/issues/270` in your PRs description, this helps us track.
 
 Thank you for your help!

**Comment by Garima-Negi** [comment]
hi, taking `content/hi/contributor-ladder/_index.md` next.

**Comment by anubha-v-ardhan** [comment]
@Garima-Negi Any updates on `content/hi/contributor-ladder/_index.md`. It's the last page required before we can launch.

**Comment by unnati914** [comment]
hey, is there any issue I can work with?

**Comment by anubha-v-ardhan** [comment]
> hey, is there any issue I can help with?

Yeah, you can take a page from checklist in this issue's which is not already assigned to someone and localize it.

**Comment by unnati914** [comment]
can I take up automation.md?

**Comment by anubhav06** [comment]
Hi! Can I work on localizing `bare_metal_machine.md` ?

**Comment by gullapalli9482** [comment]
can I take up transport layer security

**Comment by Shivansh-yadav13** [comment]
Hi, I would like to contribute to **content/hi/blue_green_deployment.md**

**Comment by jaynarayan20** [comment]
is there anything i can help with? i would love to contribute in hindi glossary.

**Comment by testsabirweb** [comment]
Hi, I would like to contribute to content/hi/service_mesh.md

**Comment by anubha-v-ardhan** [comment]
Closing this issue as we don't have plans to use this anymore and we're doing the traditional make issue -> wait for triage -> make PR way
