### ISSUE TITLE
[bn] make perfectly update bn compared to en 

### ISSUE THREAD

**Issue by asem-hamid** [cncf/glossary#2896]
Hello folks we are only this much behind from en . We will become identical very soon , if i miss something just add here .

```[tasklist]
### Tasks
- [x] update content/bn/style-guide/_index.md
- [x] update content/bn/_TEMPLATE.md
- [x] update content/bn/_index.md
- [x] update content/bn/auto-scaling.md
- [x] update content/en/bare-metal-machine.md
- [x] update content/bn/data-center.md
- [x] localize content/en/digital-certificate.md
- [x] update content/bn/kubernetes.md
- [x] update content/bn/observability.md
```

Tracking Issue: https://github.com/cncf/glossary/issues/410
related PR  : #2894

**Comment by asem-hamid** [comment]
Hello folks we are now  identical to en . Check out this [PR](https://github.com/cncf/glossary/pull/2894) .
