### ISSUE TITLE
[New term] `Hypervisor`

### ISSUE THREAD

**Issue by NitishRawat123** [cncf/glossary#3002]
#### What this term is about? (briefly)
- This term is related to virtualisation.
#### Why this term needs to be added? (briefly) 
- Often folks who are new to cloud native world found it difficult to understand.

### 2. Checklist

- [X] The suggested term fits the [cloud native definition](https://github.com/cncf/toc/blob/main/DEFINITION.md) or is essential to understanding cloud native terms. (We hope to avoid adding general or broad terminologies)
- [X] There is no existing issue yet. [(shift+click to check existing issues)](https://github.com/cncf/glossary/issues?q=label%3A%22new+term%22)
- [X] The term has not already been declined in the past. [(shift+click to check)](https://github.com/cncf/glossary/issues?q=is%3Aissue+is%3Aclosed+label%3A%22triage%2Fnot+accepted%22)
- [X] The term does not already exist in the [glossary](https://glossary.cncf.io) as a completed term, nor does it exist in [this directory](https://github.com/cncf/glossary/tree/main/content/en) as an incomplete term. (If the status of the term is `Feedback Appreciated`, consider updating the term.)
- [X] I understand that maintainers will assess if the term should be part of the Glossary. (Please be patient)
- [X] I want to work on this term and confirm that I meet the criteria as outlined in "[who can contribute](https://glossary.cncf.io/contribute/#who-can-contribute)". (If not checked, maintainers will assign another volunteer)

### (Note)

Maintainers will assign a label after assessment procedure. 
(from `triage/awaiting` to `triage/accepted` or `triage/not accepted`)

A contributor can be assigned to this issue after the issue get the `triage/accepted` label.
The assignee needs to check [Style Guide](https://glossary.cncf.io/style-guide/).

```[tasklist]
### Tasks
```

**Comment by NitishRawat123** [comment]
if this term gets accepted please do assign it to me.

**Comment by seokho-son** [comment]
Hi @NitishRawat123 
Thank you for the suggestion, but the term Hypervisor is already suggested and currently in a draft status (looking for enhancement). 

 - https://github.com/cncf/glossary/blob/main/content/en/hypervisor.md
 - https://github.com/cncf/glossary/issues/1306

Let me close this duplicated issue. 
Feel free to look forward another contribution. You may enhance the existing en/hypervisor.md. :)

**Comment by NitishRawat123** [comment]
anyway thanks for the reply and would love to contribute
