### ISSUE TITLE
Tracking Bengali Localization Progress of Glossary

### ISSUE THREAD

**Issue by mitul3737** [cncf/glossary#410]
This issue tracks Bengali localization progress.

# Join the Slack

- Join the [CNCF Slack](https://cloud-native.slack.com/join/shared_invite/zt-11yzivnzq-hs12vUAYFZmnqE3r7ILz9A#/shared-invite/email)
- Join the [glossary](https://cloud-native.slack.com/messages/glossary), [ glossary localization channel](https://cloud-native.slack.com/messages/glossary-localizations) , [Bengali localization channel](https://cloud-native.slack.com/messages/glossary-localization-bengali)

# Checklist to translate a term
1.	Check that no one else has claimed the page in the comments below.
2.	Comment below the page that you would like to localize, focus on one page per PR, at a time.
2.	Comment below the page that you would like to localize, focus on one page per PR, at a time.
3.	Maintainers will add your username and Pull Request next to your selected page in the below checklist.
4.	Fork this repo, make your localizations, and submit a pull request following the name convention ``[bn]  Localize <file_name.md>``.
ex: [bn] Localize cloud_native_apps.md
5.	tag/ping a maintainer to make it easier to track progress

# Points to remember:

- Please use the word localization instead of translation.

- For more information on how to contribute, check out [guidelines](https://glossary.cncf.io/contribute/)

# For Volunteers
Volunteers can comment below on this issue with the page-name they are interested in localizing.
Please also provide a placeholder PR in your comment.
Example: ``I would like to contribute to content/bn/<xyz.md>``

# To create a PR:
To create a PR:

- Fork https://github.com/cncf/glossary/tree/dev-bn repository to your personal account

- Create a branch with name suitable for your assigned task ``e.g. Localize content/bn/style-guide/_index.md``

- Once the changes are made, create a pull request (PR) against ``cncf:dev-bn`` from ``<your-github-id>:<branch-name>``

For example:

![O_pr](https://user-images.githubusercontent.com/57193846/153064308-ac3aecc3-e513-4a74-86cb-e056427b084e.png)

- Mention this issue link in the PR description

- NOTE: Please create 1 PR for a single page from tasks below. This makes it easier to track progress.

# Priorities
We need at least 10 terms in Hindi before go live, below are some suggested terms to work:

Minimum 10 terms required:

- [ ] config.toml
  content/bn/_index.md
  content/bn/cloud_native_tech.md
  content/bn/contribute/_index.md
  content/bn/style-guide/_index.md
  i18n/bn.toml

- [ ] content/bn/abstraction.md  
- [ ] content/bn/agile_software_development.md
- [ ] content/bn/application_programming_interface.md
- [ ] content/bn/auto_scaling.md
- [ ] content/bn/cloud_computing.md
- [ ] content/bn/cluster.md
- [ ] content/bn/containerization.md
- [ ] content/bn/devops.md
- [ ] content/bn/container.md
- [ ] content/bn/container-image.md

Additional good to have terms:

- [ ] content/bn/api_gateway.md
- [ ] content/bn/bare_metal_machine.md
- [ ] content/bn/blue_green_deployment.md
- [ ] content/bn/canary_deployment.md
- [ ] content/bn/client_server_architecture.md
- [ ] content/bn/cloud_native_apps.md
- [ ] content/bn/cloud_native_security.md
- [ ] content/bn/continuous_delivery.md
- [ ] content/bn/continuous_integration.md

**Comment by mitul3737** [comment]
Completed merging minimum contents. Repository link : #370  ( config.toml, content/bn/_index.md, content/bn/cloud_native_tech.md, content/bn/contribute/_index.md, content/bn/style-guide/_index.md, i18n/bn.toml)

**Comment by mitul3737** [comment]
I'll take ``content/bn/cloud_native_security.md``

**Comment by Saber307** [comment]
Can I please contribute to ``content/bn/container.md`` ?

**Comment by MahibulHaque** [comment]
Can I please contribute to `content/bn/agile_software_development.md` ?

**Comment by mitul3737** [comment]
@MahibulHaque  yes, you can work with that. Let me know when you create a PR. 😁

**Comment by nazma1234** [comment]
Can I work on ``content/bn/cluster.md`` ?

**Comment by mitul3737** [comment]
Yes @nazma1234  🙌

**Comment by Mouly22** [comment]
I would like to work on ```content/bn/cloud_computing.md```

**Comment by mitul3737** [comment]
Okay sure @Mouly22

**Comment by ikramulkayes** [comment]
Want to work on application_programming_interface.md

**Comment by mitul3737** [comment]
sure , @ikramulkayes

**Comment by Mouly22** [comment]
I want to work on ```content/bn/software_as_a_service.md```

**Comment by mitul3737** [comment]
okay sure @Mouly22

**Comment by ikramulkayes** [comment]
I'll take `content/bn/devops.md`.

**Comment by mitul3737** [comment]
@ikramulkayes  can you kindly change the #433 PR name as formated in docs?

**Comment by ikramulkayes** [comment]
Oh my bad. Please check it now.

**Comment by mitul3737** [comment]
![poi](https://user-images.githubusercontent.com/57193846/154100810-01996609-2fd0-4640-8b74-f4c3ed08b297.png)
Still not updated

**Comment by ikramulkayes** [comment]
Changed it again. Check it now. @mitul3737

**Comment by mitul3737** [comment]
@ikramulkayes  Looks fine now 😊

**Comment by mitul3737** [comment]
@Mouly22  can you kindly rename the PR as formated in the docs? #427

**Comment by Mouly22** [comment]
@mitul3737 I have done it. Can you kindly check it now?

**Comment by Mahrjose** [comment]
Hey @mitul3737 , I would like to contribute to `content/bn/abstraction.md`

**Comment by mitul3737** [comment]
> @mitul3737 I would like to work on `content/bn/containerization.md`

Yes you can work on this 😊

**Comment by ikramulkayes** [comment]
Can I work on ```content/bn/auto_scaling.md``` ?

**Comment by mitul3737** [comment]
> Can I work on `content/bn/auto_scaling.md` ?

Sure!

**Comment by ikramulkayes** [comment]
I want to work on ```canary_deployment.md```

**Comment by mitul3737** [comment]
Yes, you can work with that @ikramulkayes .

**Comment by mitul3737** [comment]
@ikramulkayes , @Mouly22 , @smrafy20 , @MahibulHaque and everyone. Kindly check out the file names. The markdown filename format has been changed. We will use "-" instead of "_"

**Comment by sarkartanmay393** [comment]
Hello @mitul3737, I would like to work on `content/bn/kubernetes.md`.

**Comment by Saber382** [comment]
Hey @mitul3737 , I would like to work on `content/bn/api-gateway.md`

**Comment by mitul3737** [comment]
@Saber382 , yes you can

**Comment by sarkartanmay393** [comment]
> @sarkartanmay393, you can.

@mitul3737 I pushed `kubernetes` file and created a PR for it.

**Comment by sarkartanmay393** [comment]
Hey @mitul3737, can you assign me VM localization page ?

**Comment by mitul3737** [comment]
@sarkartanmay393 are you talking about this one ` content/bn/virtual-machine.md` ?

**Comment by sarkartanmay393** [comment]
> @sarkartanmay393 are you talking about this one ` content/bn/virtual-machine.md` ?

Yes yes. Assign it to me.

**Comment by mitul3737** [comment]
@sarkartanmay393 Yes, you can work with that. But it is suggested to mention the file name as such `content/bn/virtual-machine.md` . Don't forget to mention the file name when you localize files from next 😉

**Comment by mitul3737** [comment]
@sarkartanmay393 have you joined the slack channel for Bengali Localization yet? Do join the slack ,if you have not. The links are mentioned in the Tracking issue

**Comment by sarkartanmay393** [comment]
> @sarkartanmay393 Yes, you can work with that. But it is suggested to mention the file name as such `content/bn/virtual-machine.md` . Don't forget to mention the file name when you localize files from next 😉

Hey @mitul3737 , I have created a new PR for `content/bn/virtual_machine.md`, check that out.

**Comment by sarkartanmay393** [comment]
Hey @mitul3737 I would like to work on `content/bn/microservices.md` also.

**Comment by mitul3737** [comment]
@sarkartanmay393 yes, you can

**Comment by dibyendu02** [comment]
Hey @mitul3737 , I am Dibyendu Das, interested in contributing CNCF project. Please assign me `content/bn/client-server-architecture.md` . I was referred by my friend @sarkartanmay393 .

**Comment by mitul3737** [comment]
@dibyendu02 You have been assigned `content/bn/client-server-architecture.md`

**Comment by AbdullahArean** [comment]
Hey @mitul3737 , I am Abdullah Ibne Hanif Arean! I would like to contribute to content/bn/data-center.md. Please Assign me!

**Comment by mitul3737** [comment]
@AbdullahArean You have been assigned !

**Comment by AbdullahArean** [comment]
Hey @mitul3737 , I am Abdullah Ibne Hanif Arean! I would like to contribute to 1. content/bn/idempotence.md 
2. content/bn/service.md
3. content/bn/serverless.md
4. content/bn/scalability.md
5. content/bn/portability.md

Please Assign me!

**Comment by mitul3737** [comment]
@AbdullahArean you have been assigned. Best wishes !

**Comment by sarkartanmay393** [comment]
@mitul3737 Assign me `content/bn/chaos-engineering.md`.

**Comment by sarkartanmay393** [comment]
@dibyendu02 Any update about `client-server architecture` ? 
Join our [CNCF Slack ](https://communityinviter.com/apps/cloud-native/cncf) to communicate better with maintainers.

**Comment by mitul3737** [comment]
@sarkartanmay393 You have been assigned `content/bn/chaos-engineering.md.`

**Comment by Mehadi-Hasan-Santo** [comment]
I would like to contribute to content/bn/continuous-delivery.md

**Comment by mahbubaShifa** [comment]
I would like to contribute to content/bn/devsecops.md

**Comment by mitul3737** [comment]
@Mehadi-Hasan-Santo & @mahbubaShifa you are assigned

**Comment by contributor00** [comment]
I would like to contribute into content/bn/versioncontrol.md

**Comment by mitul3737** [comment]
@contributor00 You have been assigned

**Comment by sarkartanmay393** [comment]
@mitul3737 I want to work on `content/bn/gitops.md`

**Comment by mitul3737** [comment]
You have been assigned @sarkartanmay393 the `content/bn/gitops.md`

**Comment by sarkartanmay393** [comment]
@mitul3737 Kinldy Unassign me `content/bn/gitops.md` and assign me `content/bn/continuous-integration.md`

**Comment by mitul3737** [comment]
@sarkartanmay393 You have been assigned

**Comment by PratikDey** [comment]
Can I work on `content/bn/cloud-native-apps.md` ?

**Comment by mitul3737** [comment]
@PratikDey You have been assigned

**Comment by PratikDey** [comment]
Can I work on `content/bn/bare-metal-machine.md`?

**Comment by mitul3737** [comment]
@PratikDey You have been assigned

**Comment by noor-e-jannatnafia** [comment]
I'll take content/bn/debugging.md

**Comment by mitul3737** [comment]
@noor-e-jannatnafia You are appointed

**Comment by PratikDey** [comment]
Can I work on `content/bn/containers-as-a-service.md`?

**Comment by mitul3737** [comment]
You are appointed @PratikDey

**Comment by PratikDey** [comment]
Can I work on `content/bn/blue-green-deployment.md`?

**Comment by Arindam200** [comment]
Can I please contribute to   `content/bn/infrastructure-as-code.md` ?

**Comment by mitul3737** [comment]
@Arindam200 @PratikDey You are appointed

**Comment by Arindam200** [comment]
Can I please contribute to `content/bn/infrastructure-as-a-service.md` ?

**Comment by mitul3737** [comment]
@Arindam200 You are appointed

**Comment by Arindam200** [comment]
Can I contribute to `content/bn/loosely-coupled-architecture.md` ?

**Comment by mitul3737** [comment]
@Arindam200 You are appointed

**Comment by PratikDey** [comment]
Can I work on `content/bn/distributed-apps.md`?

**Comment by mitul3737** [comment]
@dibyendu02 Any update on the Client server architecture file?

**Comment by mitul3737** [comment]
@AbdullahArean  Any updates on your appointed files?

**Comment by mitul3737** [comment]
@Mehadi-Hasan-Santo @contributor00 @mahbubaShifa Any updates on your appointed files?

**Comment by mitul3737** [comment]
@PratikDey  You have been appointed

**Comment by Arindam200** [comment]
Can I Work on `content/bn/immutable-infrastructure.md`?

**Comment by mitul3737** [comment]
Yes @Arindam200  you can.

**Comment by abhijeet-26** [comment]
can I work on content/bn/reliability.md?

**Comment by mitul3737** [comment]
@abhijeet-26 You have been appointed

**Comment by abhijeet-26** [comment]
I want to work on content/bn/self-healing.md.

**Comment by mitul3737** [comment]
@abhijeet-26 You have been assigned.

**Comment by abhijeet-26** [comment]
I want to work on content/bn/service.md.

**Comment by mitul3737** [comment]
Done!

**Comment by mitul3737** [comment]
I have removed all of the mentions. If anyone of you are still contributing to a file, kindly  mention here. Or else we have bunch of new contributors coming. They will take away these files.

**Comment by abhijeet-26** [comment]
I want to work on content/bn/scalability.md

**Comment by mitul3737** [comment]
@abhijeet-26 You have been appointed

**Comment by abhijeet-26** [comment]
I want to work on  content/bn/service-discovery.md

**Comment by mitul3737** [comment]
@abhijeet-26 You have been appointed.

**Comment by sajibAdhi** [comment]
Can I work on `content/bn/client-server-architecture.md`?

**Comment by mitul3737** [comment]
You have been appointed @sajibAdhi

**Comment by abhijeet-26** [comment]
Can I work on  content/bn/service-proxy.md?

**Comment by sajibAdhi** [comment]
Can I work on content/bn/continuous-delivery.md?

**Comment by mitul3737** [comment]
@sajibAdhi You have been appointed. Kindly proceed.

**Comment by noor-e-jannatnafia** [comment]
Can I contribute to 'glossary/content/bn/loosely-coupled-architecture.md' and 'glossary/content/bn/tightly-coupled-architectures.md'?

**Comment by mitul3737** [comment]
You  have been appointed @noor-e-jannatnafia

**Comment by noor-e-jannatnafia** [comment]
I have created a PR for `glossary/content/bn/tightly-coupled-architectures.md`.

**Comment by mitul3737** [comment]
@noor-e-jannatnafia  You created a PR targeting `cncf:main `, I have changed this manually. Kindly don't do this.
Target `cncf:dev-bn`
I have also asked for multiple changes. Kindly have a look.

**Comment by noor-e-jannatnafia** [comment]
Okay, I'll keep that in mind.

**Comment by sajibAdhi** [comment]
Can I work on content/bn/continuous-integration.md?

**Comment by mitul3737** [comment]
@sajibAdhi You have been appointed.

**Comment by Refayatul** [comment]
Can I work on content/bn/firewall.md ?

**Comment by mitul3737** [comment]
@Refayatul You have been appointed!

**Comment by abhijeet-26** [comment]
content/bn/devsecops.md
content/bn/monolithic-apps.md

**Comment by mitul3737** [comment]
You have been appointed @abhijeet-26

**Comment by nerdynikhil** [comment]
Could I work on the following files to start with?
```
content/bn/canary-deployment.md

content/bn/database-as-a-service.md

content/bn/debugging.md
```

**Comment by mahadihassanriyadh** [comment]
Can I work on these?
content/bn/serverless.md
content/bn/observability.md

**Comment by kmsanjar47** [comment]
Can I work on these?
content/bn/nodes.md
content/bn/stateful-apps.md

**Comment by mitul3737** [comment]
@nerdynikhil , @mahadihassanriyadh , @kmsanjar47 You guys have been appointed! Kindly start contributing.

**Comment by nerdynikhil** [comment]
Can I work on the following next? @mitul3737 

```
content/bn/function-as-a-service.md
content/bn/horizontal-scaling.md
content/bn/immutable-infrastructure.md
content/bn/infrastructure-as-a-service.md
content/bn/managed-services.md
content/bn/microservices.md
content/bn/transport-layer-security.md
content/bn/versioncontrol.md
content/bn/vertical-scaling.md
content/bn/virtualization.md
content/bn/zero-trust-architecture.md
```

**Comment by mitul3737** [comment]
You have been appointed @nerdynikhil

**Comment by Refayatul** [comment]
Can i work with
content/bn/service-mesh.md
content/bn/shift-left.md
content/bn/platform-as-a-service.md
content/bn/policy-as-code.md
content/bn/mutual-transport-layer-security.md

**Comment by mitul3737** [comment]
You have been appointed @Refayatul

**Comment by abhijeet-26** [comment]
content/bn/distributed-apps.md
content/bn/distributed-systems.md

**Comment by mitul3737** [comment]
@abhijeet-26 You have been appointed!

**Comment by Refayatul** [comment]
Cani work on content/bn/site-reliability-engineering.md ?

**Comment by mitul3737** [comment]
You have been appointed @Refayatul

**Comment by mahadihassanriyadh** [comment]
Can I work on these as well?

1. content/bn/gitops.md
2. content/bn/container-image.md
3. content/bn/load-balancer.md
4. content/bn/stateless-apps.md

**Comment by mitul3737** [comment]
@mahadihassanriyadh You have been appointed!

**Comment by mahadihassanriyadh** [comment]
Can I work on this?
 content/bn/security-chaos-engineering.md

**Comment by mitul3737** [comment]
@mahadihassanriyadh  You have been appointed!

**Comment by RitamSamant** [comment]
hello, @mitul3737 I talked to @nerdynikhil can you please assign me in content/bn/zero-trust-architecture.md?

**Comment by mitul3737** [comment]
You have been appointed @RitamSamant

**Comment by ai-naymul** [comment]
Hello @mitul3737,
I would like to work on `content/en/self-healing.md` could please assign me that?
Thank you :)

**Comment by mitul3737** [comment]
@ai-naymul  , this tracking issue is only for Bengali Localization. We don't manage `en` files rather `bn` files

**Comment by ai-naymul** [comment]
> @ai-naymul , this tracking issue is only for Bengali Localization. We don't manage `en` files rather `bn` files

I mean this `content/en/self-healing.md `topic is not available in `bn` directory I will localize it into Bengali
So,should I?

**Comment by mitul3737** [comment]
@ai-naymul this file has already been localized here #1628

Kindly check the `dev-bn` branch rather than the `main` branch

**Comment by mitul3737** [comment]
@ai-naymul we have a new file `content/bn/continuous-deployment` which you can work with. Let me know if you are interested.

**Comment by mitul3737** [comment]
I have updated the Unassigned tasks and you guys can now pick any of them.
![image](https://user-images.githubusercontent.com/57193846/230323110-989f3ab9-a504-41f2-ae37-15f8eec0f0f5.png)

**Comment by ai-naymul** [comment]
> @ai-naymul we have some new file which you can work with. Let me know if you are interested.

Yes I am ,I would love to work on those

**Comment by noor-e-jannatnafia** [comment]
I would like to work on `content/bn/search.md`.

**Comment by mitul3737** [comment]
> > @ai-naymul we have some new file which you can work with. Let me know if you are interested.
> 
> Yes I am ,I would love to work on those and thanks a lot for asking :)

Kindly mention the file you want to work with.

**Comment by mitul3737** [comment]
> I would like to work on `content/bn/search.md`.

You have been appointed

**Comment by ai-naymul** [comment]
> > > @ai-naymul we have some new file which you can work with. Let me know if you are interested.
> > 
> > 
> > Yes I am ,I would love to work on those and thanks a lot for asking :)
> 
> Kindly mention the file you want to work with.

I would like to work on `content/bn/event-driven-architecture.md`

**Comment by mitul3737** [comment]
> > > > @ai-naymul we have some new file which you can work with. Let me know if you are interested.
> > > 
> > > 
> > > Yes I am ,I would love to work on those and thanks a lot for asking :)
> > 
> > 
> > Kindly mention the file you want to work with.
> 
> I would like to work on `content/bn/event-driven-architecture.md`

You have been appointed

**Comment by ai-naymul** [comment]
Hello @mitul3737 bhaiya,
I would like to work on `content/bn/event-streaming.md` file could you please assign me this 
Thank you :)

**Comment by RitamSamant** [comment]
I would like to take `content/bn/edge-computing.md` if possible.
Thank you.

**Comment by mitul3737** [comment]
@RitamSamant @ai-naymul  You guys have been appointed.

**Comment by mitul3737** [comment]
You have been appointed @sajibAdhi

**Comment by sajibAdhi** [comment]
I would like to work on `content/bn/hypervisor.md`

**Comment by mitul3737** [comment]
@sajibAdhi  You have been appointed!

**Comment by kmsanjar47** [comment]
@mitul3737 Vaia can you check my pr #1971 ?

**Comment by RitamSamant** [comment]
@mitul3737 hi, I made the changes you asked for PR #1972.

**Comment by sajibAdhi** [comment]
@mitul3737 `dev-bn` updated with `main` on this #2349

**Comment by sajibAdhi** [comment]
I am working on this issue #2858

**Comment by asem-hamid** [comment]
i am working on this issue #2294
